lectures:
  - ruby/03-iterators-blocks

lecture:
  fr:
    video: 133651894
  en:
    video: 174646677
  # Boris @ Brussels
  # en:
  #   video: 156882788
livecode:
  fr:
    video: 133677611
    gist: 76279ecab006f06626c9
