lectures:
  - ruby/04-hash-symbols

lecture:
  fr:
    video: 133756073
  en:
    video: 174803843
  # Boris @ Brussels
  # en:
  #   video: 157108052
livecode:
  fr:
    video: 133771847
    gist: 89a8ab4e39c85e1a5563
  en:
    video: 175240906 # @Adrien de Villoutreys :)

teacher_ratio: 7
comment: Quizz
