days: 1
schedule:
  ta:
    starts_at_hours: 9
    starts_at_minutes: 30

lectures:
  - setup/1-setup
  - setup/2-terminal-101
  - setup/3-git-101

lecture:
  en:
    video: 174322292

teacher_ratio: 10
