lectures:
  - ruby/01-programming-basics

lecture:
  fr:
    video: 133469359
  en:
    video: 174338406

  # Boris @ Brussels:
  # en:
  #   video: 157107780
livecode:
  fr:
    video: 133471297
    gist: 11045934a0c609a81af0
  en:
    video: 155718572
