StringLiterals:
  Enabled: false
TrailingBlankLines:
  Enabled: false
LineLength:
  Max: 120
UnusedMethodArgument:
  Enabled: false
EmptyLines:
  Enabled: false
RedundantReturn:
  Enabled: false
SelfAssignment:
  Enabled: false
Documentation:
  Enabled: false
RegexpLiteral:
  Enabled: false
GuardClause:
  Enabled: false
WordArray:
  Enabled: false

AllCops:
  Exclude:
    - '**/Rakefile'
    - '**/spec/**/*'
