lectures:
  - oop/04-modeling-data

lecture:
  fr:
    video: 134727310
  en:
    video: 176301225

livecode:
  fr:
    video: 152548274
  en:
    video: 176348499
    gist: edc840c5d9dd62a36c2faadb77290acb

teacher_ratio: 7

