schedule:
  assistant:
    ends_at_hours: 18
    ends_at_minutes: 30

help: true
lectures:
  - rails/testing
lecture:
  fr:
    video: 169102684
  en:
    video: 193540570 # Livedode only w/ errors. Should be re-done

teacher_ratio: 7

flashcard_alert: false
