schedule:
  ta:
    ends_at_hours: 18
    ends_at_minutes: 30

help: true
lectures:
  - rails/react
lecture:
  fr:
    video: 138734994
  en:
    video: 181925425

teacher_ratio: 7
comment: Demo
flashcard_alert: false
