help: true

schedule:
  ta:
    ends_at_hours: 18
    ends_at_minutes: 30

lectures:
  - rails/07-authentication
  - rails/06-git-github-workflow

lecture:
  fr:
    video: 137242820
  en:
    video: 179743979

teacher_ratio: 10

