lectures:
  - rails/01-rails-intro

lecture:
  fr:
    video: 136503175
  en:
    video: 178895411

livecode:
  fr:
    video: 136521446
  en:
    video: 178932539
    gist: c80c39bbb3b79d41ee38f8cfca31bd10

teacher_ratio: 10

