lectures:
  - db/04-active-record-advanced

lecture:
  fr:
    video: 135351878
  en:
    video: 177221729

livecode:
  fr:
    video: 135502571
  en:
    video: 177276180

teacher_ratio: 10
comment: Quizz
