lectures:
  - rails/03-rails-advanced
  - rails/extra-01-rails-front-end

lecture:
  fr:
    video: 136725134
  en:
    video: 179189739

livecode:
  fr:
    video: 136743151
  en:
    video: 179220171
    gist: bdd0078a9370aa8b09028bc82ebcec01

teacher_ratio: 10
comment: nil
