schedule:
  assistant:
    ends_at_hours: 18
    ends_at_minutes: 30

lectures:
  - rails/admin-interfaces
help: true
lecture:
  fr:
    video: 138100748
  en:
    video: 180866688

teacher_ratio: 7

