schedule:
  assistant:
    ends_at_hours: 18
    ends_at_minutes: 30

help: true
lectures:
  - rails/search
lecture:
  fr:
    video: 138609059
  en:
    video: 193547539 # Livedode only w/ errors. Should be re-done

teacher_ratio: 7

flashcard_alert: false
