lectures:
  - front/04-middleman

lecture:
  fr:
    video: 153906321
  en:
    video: 178008447

livecode:
  fr:
    video: 153800041
  en:
    video: 178053786

# # Old
# video: 135954622
# livecode:
#   video: 153800041
#   gist: cba333c6eedbe0eea525

teacher_ratio: 10
comment: Pitches
