instructions: false
lectures:
  - rails/04-hosting-deployment

lecture:
  fr:
    video: 137223612
  en:
    video: 179355085

livecode:
  fr:
    video: 136844098
  en:
    video: 179354202
    gist: 02d062d3fed3217832c9aa88e9953c19

teacher_ratio: 8

