schedule:
  ta:
    starts_at_hours: 9
    starts_at_minutes: 30

lecture:
  fr:
    video: 134819648
  en:
    video: 176440453

livecode:
  fr:
    video: 134868598
  en:
    video: 176492237
    gist: a2d3fc1f5ea9ed41ced161c23d7a4ff9

flashcard_alert: false

teacher_ratio: 7

