help: true

schedule:
  assistant:
    ends_at_hours: 18
    ends_at_minutes: 30

lectures:
  - rails/09-fb-connect

lecture:
  fr:
    video: 137231961
  en:
    video: 179878098

teacher_ratio: 10

