lectures:
  - ruby/02-flow-and-array

lecture:
  fr:
    video: 133547571
  en:
    video: 174505542
  # Boris version in Belgium
  # en:
  #   video: 156882630

livecode:
  fr:
    video: 133575663
    gist: 97d46d7ea7ba10698c73
  en:
    video: 155718621

teacher_ratio: 8
comment: nil
